name: cell
description: cell feature

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5

  freezed_annotation:
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.3.5

  flutter_portal:
  atreeon_get_child_size: ^0.1.1+1

  collection: ^1.18.0

  # design system
  design_system:
    path: ../../core/design_system

  utils:
    path: ../../core/utils

  # feature
  llm:
    path: ../../feature/llm
  google_generative_ai:

  mix: ^1.4.0
  iconly:
  line_icons:

  flutter_animate:

  flutter_markdown:

  flextras:

  any_link_preview: ^3.0.2
  http: ^1.2.2

  # This is unsure the best db
  hive: ^2.2.3
  drift: ^2.20.0
  drift_flutter: ^0.2.0

  rxdart: ^0.28.0

  url_launcher: ^6.3.0

dependency_overrides:
  web: ^1.0.0
  drift:
    git:
      url: https://github.com/simolus3/drift.git
      ref: develop
      path: drift
  drift_dev:
    git:
      url: https://github.com/simolus3/drift.git
      ref: develop
      path: drift_dev
  sqlparser:
    git:
      url: https://github.com/simolus3/drift.git
      ref: develop
      path: sqlparser

dev_dependencies:
  build_runner: ^2.4.11
  freezed:
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  drift_dev: ^2.20.0

