name: gemboard_app
description: "gemboard mobile app"
publish_to: "none"
version: 0.0.12+12

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # native things
  bitsdojo_window: ^0.1.6

  # Dependencies
  flutter_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1

  sliver_tools: ^0.2.12
  iconly: ^1.0.1

  flutter_portal: ^1.1.4

  # Infinity canvas
  boundless_stack:
    git:
      url: https://github.com/definev/boundless_stack.git
      ref: main

  # Theme
  mix: ^1.4.0
  design_system:
    path: ../../core/design_system

  # Navigator
  gemboard_navigator:
    path: ../gemboard_navigator

  # Configuration
  gemboard_configuration:
    path: ../gemboard_configuration

  # Database
  gemboard_database:
    path: ../gemboard_database

  gemboard_common:
    path: ../gemboard_common

dev_dependencies:
  flutter_lints: ^4.0.0
  icons_launcher: ^2.1.7
  msix: ^3.16.7
  inno_bundle: ^0.6.0

dependency_overrides:
  flutter_keyboard_visibility_web:
    git:
      url: https://github.com/definev/flutter_keyboard_visibility.git
      ref: master
      path: flutter_keyboard_visibility_web

icons_launcher:
  image_path: "assets/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    macos:
      image_path: "assets/macos_logo.png"
      enable: true
    web:
      enable: true
      favicon_path: "assets/favicon.png"
    windows:
      enable: true
    linux:
      enable: true

flutter:
  uses-material-design: true

inno_bundle:
  id: 52cb865d-154d-5f6e-95a9-b1ec55455064
  publisher: zennn.mind # Optional, but recommended.
  name: Gemboard # Also optional, but recommended.