name: home
description: home feature

environment: 
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5

  freezed_annotation:
  json_annotation: ^4.9.0

  flutter_portal: ^1.1.4
  sliver_tools:
  
  flutter_animate:
  
  boundless_stack:
    git:
      url: https://github.com/definev/boundless_stack.git
      ref: main
  
  # design system
  design_system:
    path: ../../core/design_system
  
  # common
  gemboard_common:
    path: ../../app/gemboard_common
  
  utils:
    path: ../../core/utils

  # feature
  whiteboard: 
    path: ../../feature/whiteboard
  settings:
    path: ../../feature/settings
  folder:
    path: ../../feature/folder
  llm:
    path: ../../feature/llm
  import_export:
    path: ../../feature/import_export
  
  mix: ^1.4.0
  flextras: ^1.0.0
  iconly: ^1.0.1

dependency_overrides:
  web: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.11
  freezed:
  json_serializable: ^6.8.0
