name: genit_navigator
description: "genit mobile app"
publish_to: "none"
version: 0.0.1+1

environment: 
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  bitsdojo_window: 
  bitsdojo_window_platform_interface:

  flutter_portal: ^1.1.4
  
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0

  flextras: ^1.0.0
  design_system:
    path: ../../core/design_system
  mix: ^1.2.0
  utils:
    path: ../../core/utils

  # feature
  home:
    path: ../../feature/home
  whiteboard:
    path: ../../feature/whiteboard

dev_dependencies:
  build_runner: ^2.3.3
  build_verify: 
  go_router_builder: ^2.7.0
  

flutter:
  uses-material-design: true