name: utils
description: utils feature

environment: 
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  intl: ^0.20.2

  collection: ^1.18.0 

  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5

  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  flow_builder: ^0.1.0 

  uuid: 

  boxy: ^2.2.0

  # database
  hive: ^2.2.3 
  shared_preferences: ^2.3.2

  http: ^1.2.2
  html: ^0.15.4
  string_validator: ^1.1.0

  flutter_svg: ^2.0.10+1
  vector_graphics_codec: ^1.1.11+1

dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0
