name: whiteboard
description: whiteboard feature

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  collection: ^1.18.0

  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5

  freezed_annotation: ^2.4.3
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.3.5

  iconly: ^1.0.1
  line_icons: ^2.0.2

  flutter_portal:
  atreeon_get_child_size:

  # Native
  super_drag_and_drop: ^0.8.19

  # design system
  design_system:
    path: ../../core/design_system
  gemboard_common:
    path: ../../app/gemboard_common

  # feature
  home:
    path: ../../feature/home
  cell:
    path: ../../feature/cell
  graph_edge:
    path: ../../feature/graph_edge
  folder:
    path: ../../feature/folder
  settings:
    path: ../../feature/settings
  import_export:
    path: ../../feature/import_export

  # utils
  utils:
    path: ../../core/utils
  
  sliver_tools: ^0.2.12
  
  super_clipboard: ^0.8.19

  boundless_stack:
    git:
      url: https://github.com/definev/boundless_stack.git
      ref: main

  mix: ^1.4.0

  # native
  path_provider: ^2.1.0
  flutter_keyboard_visibility: ^6.0.0

  flextras:
  # Database
  # This is unsure the best db
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  drift: ^2.20.0
  drift_flutter: ^0.2.0

dependency_overrides:
  web: ^1.0.0
  drift:
    git:
      url: https://github.com/simolus3/drift.git
      ref: develop
      path: drift
  drift_dev:
    git:
      url: https://github.com/simolus3/drift.git
      ref: develop
      path: drift_dev
  sqlparser:
    git:
      url: https://github.com/simolus3/drift.git
      ref: develop
      path: sqlparser

dev_dependencies:
  build_runner: ^2.4.11
  freezed:
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  drift_dev: ^2.20.0
