name: whiteboard
description: whiteboard feature

environment: 
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  cupertino_icons: ^1.0.8

  collection: ^1.18.0

  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5

  freezed_annotation: ^2.4.3
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.3.5

  iconly: ^1.0.1
  line_icons: ^2.0.2

  flutter_portal: 
  atreeon_get_child_size: 
  
  # Native
  super_drag_and_drop: ^0.8.17 
  
  # design system
  design_system:
    path: ../../core/design_system
  gemboard_common:
    path: ../../app/gemboard_common
  
  # feature
  cell:
    path: ../../feature/cell
  graph_edge:
    path: ../../feature/graph_edge

  # utils
  utils:
    path: ../../core/utils 

  boundless_stack:
    git:
      url: https://github.com/definev/boundless_stack.git
      ref: main
  
  # Database
  hive: ^2.2.3
  shared_preferences: 
  
  mix: ^1.2.0
  
  flextras:

dev_dependencies:
  build_runner: ^2.3.3
  freezed:
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0