name: design_system

description: "design system for genit"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  flex_color_scheme: ^7.3.1
  mix:
  equatable: 
  iconify_flutter_plus:
  flextras:
  flutter_hooks: ^0.20.5
  confetti:
  smooth_sheets: 

flutter:
  uses-material-design: true