name: design_system

description: "design system for genit"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  flutter_hooks: ^0.20.5
  equatable: 
  flextras:
  smooth_sheets: 

  boundless_stack:
    path: ../../../boundless_stack

  google_fonts: 
  mix: ^1.2.0
  iconly: ^1.0.1

  flutter_shaders: ^0.1.2

flutter:
  uses-material-design: true
  shaders:
    - assets/shaders/grid_background.frag