name: design_system

description: "design system for genit"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  flutter_hooks: ^0.20.5
  equatable: 
  flextras:
  smooth_sheets: 

  google_fonts: 
  mix: ^1.2.0
  iconly: ^1.0.1

flutter:
  uses-material-design: true