name: design_system

description: "design system for genit"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  flutter_hooks: ^0.20.5
  equatable: 
  flextras:
  smooth_sheets: 
  sliver_tools: ^0.2.12

  boundless_stack:
    git:
      url: https://github.com/definev/boundless_stack.git
      ref: main

  google_fonts: 
  mix: ^1.2.0
  iconly: ^1.0.1

  flutter_shaders: ^0.1.2
  emoji_selector: ^0.0.6

flutter:
  uses-material-design: true
  shaders:
    - assets/shaders/grid_background.frag