name: import_export
description: import_export feature

environment: 
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5

  freezed_annotation:
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.3.5

  
  # design system
  design_system:
    path: ../../core/design_system
  utils:
    path: ../../core/utils
  
  # feature
  whiteboard:
    path: ../../feature/whiteboard
  cell:
    path: ../../feature/cell
  graph_edge:
    path: ../../feature/graph_edge
  folder:
    path: ../../feature/folder
  
  mix: ^1.4.0
  sliver_tools: ^0.2.12
  
  
  flextras:
  
  # file picker
  file_picker: ^8.0.6
  path_provider: ^2.1.0

dependency_overrides:
  web: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.11
  freezed:
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
