name: llm
description: llm feature

environment: 
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.5 

  freezed_annotation:
  json_annotation: ^4.9.0

  google_generative_ai: 
  
  # design system
  design_system:
    path: ../../core/design_system
  
  
  mix: ^1.4.0
  
  shared_preferences: ^2.3.2
  
  flextras:
  

dev_dependencies:
  build_runner: ^2.4.11
  freezed:
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
