name: gemboard_navigator
description: "gemboard mobile app"
publish_to: "none"
version: 0.0.1+1

environment: 
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  bitsdojo_window: 
  bitsdojo_window_platform_interface:

  flutter_portal: ^1.1.4
  
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.1
  cupertino_modal_sheet: ^1.1.0

  flextras: ^1.0.0
  design_system:
    path: ../../core/design_system
  mix: ^1.4.0
  utils:
    path: ../../core/utils

  # feature
  settings:
    path: ../../feature/settings
  home:
    path: ../../feature/home
  whiteboard:
    path: ../../feature/whiteboard
  import_export:
    path: ../../feature/import_export
  folder:
    path: ../../feature/folder

dev_dependencies:
  build_runner: ^2.4.11
  build_verify: 
  go_router_builder: ^2.7.0
  
dependency_overrides:
  web: ^1.0.0

flutter:
  uses-material-design: true