name: ask_board
description: ask_board feature

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5

  riverpod_annotation: ^2.3.5
  freezed_annotation:
  json_annotation: ^4.9.0
  osum_serializable: 0.0.5

  # id
  uuid: ^3.0.6

  flextras: ^1.0.0

  # widget canvas
  boundless_stack:
    path: ../../../boundless_stack
    # git:
    #   url: https://github.com/definev/boundless_stack.git
    #   ref: main
  equatable: ^2.0.5

  # design system
  design_system:
    path: ../../core/design_system

dev_dependencies:
  build_runner: ^2.3.3
  freezed:
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0

dependency_overrides:
  uuid: ^3.0.6
