name: Build
on:
  push:
    branches: ["release"]
  pull_request:
    branches: ["release"]

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: master
      - name: Melos
        uses: bluefireteam/melos-action@v3
        with:
          run-bootstrap: true
      - run: melos exec --scope="*app*" -- flutter build ios --release --no-codesign
      - run: melos exec --scope="*app*" -- flutter build apk

  build_web:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: master
      - name: Melos
        uses: bluefireteam/melos-action@v3
        with:
          run-bootstrap: true
      - run: melos exec --scope="*app*" -- flutter build web --web-renderer=canvaskit
  build_web_wasm:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: master
      - name: Melos
        uses: bluefireteam/melos-action@v3
        with:
          run-bootstrap: true
      - run: melos exec --scope="*app*" -- flutter build web --wasm
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: master
      - name: Melos
        uses: bluefireteam/melos-action@v3
        with:
          run-bootstrap: true
      - run: melos exec --scope="*app*" -- flutter build windows
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: master
      - name: Melos
        uses: bluefireteam/melos-action@v3
        with:
          run-bootstrap: true
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: melos exec --scope="*app*" -- flutter build linux
