name: Build
on:
  push:
    branches: ["release"]
    tags:
      - '*'
  pull_request:
    branches: ["release"]

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: master
      - name: Melos
        uses: bluefireteam/melos-action@v3
        with:
          run-bootstrap: true
      - run: melos exec --scope="*app*" -- flutter build ios --release --no-codesign
      - run: melos exec --scope="*app*" -- flutter build apk
      - name: '📦 Package Android & iOS'
        run: |
          cd ${{github.workspace}}
          zip -r ios.zip app/gemboard_app/build/ios/iphoneos/Runner.app
          gh release upload ${{github.event.release.tag_name}} ios.zip
          zip -r android.zip app/gemboard_app/build/app/outputs/flutter-apk/app-release.apk
          gh release upload ${{github.event.release.tag_name}} android.zip
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash

  build_web:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: master
      - name: Melos
        uses: bluefireteam/melos-action@v3
        with:
          run-bootstrap: true
      - run: melos exec --scope="*app*" -- flutter build web --web-renderer=canvaskit
      - name: '📦 Package Web'
        run: |
          cd ${{github.workspace}}
          zip -r web.zip app/gemboard_app/build/web
          gh release upload ${{github.event.release.tag_name}} web.zip
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash
  build_web_wasm:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: master
      - name: Melos
        uses: bluefireteam/melos-action@v3
        with:
          run-bootstrap: true
      - run: melos exec --scope="*app*" -- flutter build web --wasm
      - name: '📦 Package Web (WASM)'
        run: |
          cd ${{github.workspace}}
          zip -r web_wasm.zip app/gemboard_app/build/web
          gh release upload ${{github.event.release.tag_name}} web_wasm.zip
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: master
      - name: Melos
        uses: bluefireteam/melos-action@v3
        with:
          run-bootstrap: true
      - run: melos exec --scope="*app*" -- flutter build windows
      - name: '📦 Package Windows'
        run: |
          cd ${{github.workspace}}
          zip -r windows.zip app/gemboard_app/build/windows
          gh release upload ${{github.event.release.tag_name}} windows.zip
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: master
      - name: Melos
        uses: bluefireteam/melos-action@v3
        with:
          run-bootstrap: true
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: melos exec --scope="*app*" -- flutter build linux
      - name: '📦 Package Linux'
        run: |
          cd ${{github.workspace}}
          zip -r linux.zip app/gemboard_app/build/linux
          gh release upload ${{github.event.release.tag_name}} linux.zip
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash
